"""LEVEE — Floodgate management prototype.

During a 90-second storm, operate three sluice gates to route water down a
stack of reservoirs and out through a turbine. Holding water high boosts head
pressure (and thus power output) but risks an overflow. Anticipate periodic
surge waves, ride the edge of breach, and bank as much power as possible.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass
from enum import Enum

import pyxel

# --- Color constants (raw ints) ---
BLACK = 0
NAVY = 1
PURPLE = 2
GREEN = 3
BROWN = 4
DARK_BLUE = 5
LIGHT_BLUE = 6
WHITE = 7
RED = 8
ORANGE = 9
YELLOW = 10
LIME = 11
CYAN = 12
GRAY = 13
PINK = 14
PEACH = 15

# --- Simulation constants ---
TANKS = 3
CAPACITY = 100.0
GATE_FLOW = 5.0
BASE_RAIN_MIN = 1.0
BASE_RAIN_MAX = 2.0
STORM_DURATION = 5400
SURGE_INTERVAL = 600
SURGE_DURATION = 180
SURGE_WARNING = 120
SURGE_MULT = 3.0
CLEAR_BONUS_PER_WATER = 2.0

# --- Geometry ---
TANK_X = 20
TANK_W = 280
TANK_H = 48
TANK_YS = (30, 94, 158)
GATE_YS = (78, 142, 206)
GATE_H = 12


class Phase(Enum):
    TITLE = "title"
    PLAYING = "playing"
    GAME_OVER = "game_over"


@dataclass
class Particle:
    x: float
    y: float
    vx: float
    vy: float
    life: int
    color: int


@dataclass
class FloatText:
    x: float
    y: float
    text: str
    life: int
    color: int


# --- Pure module-level functions (headless-testable, no pyxel) ---


def in_surge(frame: int) -> bool:
    """True during the surge window (the last SURGE_DURATION frames of each cycle)."""
    return frame % SURGE_INTERVAL >= SURGE_INTERVAL - SURGE_DURATION


def surge_warning(frame: int) -> bool:
    """True during the SURGE_WARNING frames immediately before a surge starts."""
    cycle = frame % SURGE_INTERVAL
    start = SURGE_INTERVAL - SURGE_DURATION - SURGE_WARNING
    end = SURGE_INTERVAL - SURGE_DURATION
    return start <= cycle < end


def rain_rate(frame: int) -> float:
    """Inflow this frame: base ramp, tripled during a surge. Never negative."""
    base = BASE_RAIN_MIN + (BASE_RAIN_MAX - BASE_RAIN_MIN) * (frame / STORM_DURATION)
    if in_surge(frame):
        base *= SURGE_MULT
    return max(0.0, base)


def power_gain(flow: float, head_level: float) -> int:
    """Power generated by `flow` of water exiting the turbine at `head_level`."""
    return int(flow * (1.0 + head_level / CAPACITY))


class Game:
    phase: Phase = Phase.TITLE
    frame: int = 0
    levels: list[float]
    gates: list[bool]
    power: float = 0.0
    score: int = 0
    best_score: int = 0
    cleared: bool = False
    particles: list[Particle] = []
    floats: list[FloatText] = []
    shake_frames: int = 0
    flash_frames: int = 0
    surge_flash: int = 0

    def __init__(self) -> None:
        pyxel.init(320, 240, title="LEVEE", display_scale=2)
        self.best_score = 0
        self.reset()
        self.phase = Phase.TITLE
        pyxel.run(self.update, self.draw)

    def reset(self) -> None:
        self.phase = Phase.PLAYING
        self.frame = 0
        self.levels = [0.0] * TANKS
        self.gates = [False] * TANKS
        self.power = 0.0
        self.score = 0
        self.cleared = False
        self.particles = []
        self.floats = []
        self.shake_frames = 0
        self.flash_frames = 0
        self.surge_flash = 0

    # --- Logic (pyxel-free) ---

    def _toggle_gate(self, i: int) -> None:
        self.gates[i] = not self.gates[i]
        gx, gy, gw, gh = self._gate_rect(i)
        for _ in range(4):
            self.particles.append(
                Particle(
                    x=gx + random.uniform(0, gw),
                    y=gy + random.uniform(0, gh),
                    vx=random.uniform(-0.5, 0.5),
                    vy=random.uniform(-0.6, 0.1),
                    life=12,
                    color=CYAN if self.gates[i] else GRAY,
                )
            )

    def _check_breach(self) -> bool:
        return any(level > CAPACITY for level in self.levels)

    def _apply_tick(self) -> None:
        # 1. Rain fills the top tank.
        self.levels[0] += rain_rate(self.frame)

        # 2. Gate 0: tank0 -> tank1.
        if self.gates[0]:
            flow = min(GATE_FLOW, self.levels[0])
            self.levels[0] -= flow
            self.levels[1] += flow

        # 3. Gate 1: tank1 -> tank2.
        if self.gates[1]:
            flow = min(GATE_FLOW, self.levels[1])
            self.levels[1] -= flow
            self.levels[2] += flow

        # 4. Gate 2: tank2 -> turbine/out (head captured before subtracting).
        if self.gates[2]:
            head = self.levels[2]
            flow = min(GATE_FLOW, self.levels[2])
            if flow > 0:
                self.levels[2] -= flow
                gain = power_gain(flow, head)
                self.power += gain
                self.floats.append(FloatText(250, 192, f"+{gain}", 40, YELLOW))
                self.particles.append(
                    Particle(
                        x=304,
                        y=212,
                        vx=random.uniform(-2.0, -1.0),
                        vy=random.uniform(-1.0, 1.0),
                        life=15,
                        color=YELLOW,
                    )
                )

    def _spawn_rain_particles(self, n: int) -> None:
        for _ in range(n):
            self.particles.append(
                Particle(
                    x=random.uniform(0, 320),
                    y=random.uniform(0, 24),
                    vx=0.0,
                    vy=random.uniform(2.0, 4.0),
                    life=random.randint(15, 30),
                    color=LIGHT_BLUE,
                )
            )

    def _spawn_breach_burst(self) -> None:
        cx, cy = 160, 150
        for _ in range(20):
            ang = random.uniform(0, 2 * math.pi)
            sp = random.uniform(1.0, 4.0)
            self.particles.append(
                Particle(
                    x=cx,
                    y=cy,
                    vx=math.cos(ang) * sp,
                    vy=math.sin(ang) * sp,
                    life=random.randint(20, 40),
                    color=RED,
                )
            )

    def _update_particles(self) -> None:
        for p in self.particles:
            p.x += p.vx
            p.y += p.vy
            p.vy += 0.05
            p.life -= 1
        self.particles = [p for p in self.particles if p.life > 0]

    def _update_floats(self) -> None:
        for f in self.floats:
            f.y -= 0.3
            f.life -= 1
        self.floats = [f for f in self.floats if f.life > 0]

    def _update_playing(self) -> None:
        self.frame += 1
        self.surge_flash = 1 if surge_warning(self.frame) else 0
        self._apply_tick()
        self._spawn_rain_particles(int(rain_rate(self.frame)) + 1)

        if self._check_breach():
            self.phase = Phase.GAME_OVER
            self.cleared = False
            self.shake_frames = 20
            self.flash_frames = 20
            self._spawn_breach_burst()
            self.floats.append(FloatText(148, 120, "BREACH", 60, RED))
        elif self.frame >= STORM_DURATION:
            self.phase = Phase.GAME_OVER
            self.cleared = True
            self.power += sum(self.levels) * CLEAR_BONUS_PER_WATER
            self.floats.append(FloatText(120, 120, "STORM CLEARED", 60, YELLOW))

        self._update_particles()
        self._update_floats()
        self.score = int(self.power)
        if self.phase == Phase.GAME_OVER and self.score > self.best_score:
            self.best_score = self.score

    # --- Geometry helpers ---

    def _tank_rect(self, i: int) -> tuple[int, int, int, int]:
        return (TANK_X, TANK_YS[i], TANK_W, TANK_H)

    def _gate_rect(self, i: int) -> tuple[int, int, int, int]:
        return (TANK_X, GATE_YS[i], TANK_W, GATE_H)

    # --- Pyxel lifecycle ---

    def update(self) -> None:
        if self.phase == Phase.TITLE:
            if pyxel.btnp(pyxel.KEY_RETURN) or pyxel.btnp(pyxel.MOUSE_BUTTON_LEFT):
                self.reset()
        elif self.phase == Phase.PLAYING:
            for i in range(TANKS):
                if pyxel.btnp(getattr(pyxel, f"KEY_{i + 1}")):
                    self._toggle_gate(i)
            if pyxel.btnp(pyxel.MOUSE_BUTTON_LEFT):
                mx, my = pyxel.mouse_x, pyxel.mouse_y
                for i in range(TANKS):
                    gx, gy, gw, gh = self._gate_rect(i)
                    if gx <= mx <= gx + gw and gy <= my <= gy + gh:
                        self._toggle_gate(i)
            self._update_playing()
        elif self.phase == Phase.GAME_OVER:
            if pyxel.btnp(pyxel.KEY_RETURN) or pyxel.btnp(pyxel.MOUSE_BUTTON_LEFT):
                self.reset()

        if self.shake_frames > 0:
            self.shake_frames -= 1
            ox = random.randint(-3, 3)
            oy = random.randint(-3, 3)
            try:
                pyxel.camera(ox, oy)
            except BaseException:
                pass
        else:
            try:
                pyxel.camera(0, 0)
            except BaseException:
                pass
        if self.flash_frames > 0:
            self.flash_frames -= 1

    def draw(self) -> None:
        if self.phase == Phase.TITLE:
            self._draw_title()
        elif self.phase == Phase.PLAYING:
            self._draw_playing()
        elif self.phase == Phase.GAME_OVER:
            self._draw_game_over()

    def _draw_title(self) -> None:
        pyxel.cls(NAVY)
        pyxel.text(150, 70, "LEVEE", YELLOW)
        pyxel.text(118, 88, "Floodgate Operator", LIGHT_BLUE)
        pyxel.text(60, 118, "Hold water high for power.", WHITE)
        pyxel.text(72, 128, "Don't overflow!", WHITE)
        pyxel.text(40, 150, "Keys 1/2/3 toggle gates", GRAY)
        pyxel.text(48, 160, "Click gates to toggle", GRAY)
        pyxel.text(100, 182, "ENTER to start", LIME)

    def _draw_playing(self) -> None:
        pyxel.cls(NAVY)

        # Rain cloud at top.
        pyxel.rect(0, 6, 320, 18, DARK_BLUE)
        for cx in range(0, 320, 32):
            pyxel.circ(cx + 16, 14, 8, DARK_BLUE)

        # Tanks with water fill from the bottom up.
        for i in range(TANKS):
            x, y, w, h = self._tank_rect(i)
            pyxel.rectb(x, y, w, h, WHITE)
            lvl = self.levels[i]
            color = RED if lvl > 85 else LIGHT_BLUE
            fill_h = int((min(lvl, CAPACITY) / CAPACITY) * h)
            if fill_h > 0:
                pyxel.rect(x + 1, y + h - fill_h - 1, w - 2, fill_h, color)

        # Gates.
        for i in range(TANKS):
            gx, gy, gw, gh = self._gate_rect(i)
            color = CYAN if self.gates[i] else GRAY
            pyxel.rect(gx, gy, gw, gh, color)
            pyxel.rectb(gx, gy, gw, gh, WHITE)
            pyxel.text(gx + 4, gy + 2, str(i + 1), BLACK)

        # HUD.
        frac = max(0.0, (STORM_DURATION - self.frame) / STORM_DURATION)
        pyxel.rect(8, 8, 80, 6, GRAY)
        pyxel.rect(8, 8, int(80 * frac), 6, LIME)
        pyxel.text(200, 8, f"POWER {self.score}", YELLOW)
        pyxel.text(200, 16, f"BEST {self.best_score}", GRAY)

        # Surge warnings.
        if surge_warning(self.frame) and (self.frame % 30 < 15):
            pyxel.text(132, 100, "SURGE WARNING!", RED)
        if in_surge(self.frame):
            pyxel.text(148, 116, "SURGE", ORANGE)

        # Particles and floating text.
        for p in self.particles:
            pyxel.pset(int(p.x), int(p.y), p.color)
        for f in self.floats:
            pyxel.text(int(f.x), int(f.y), f.text, f.color)

        if self.flash_frames > 0 and self.flash_frames % 4 < 2:
            pyxel.rect(0, 0, 320, 240, RED)

    def _draw_game_over(self) -> None:
        pyxel.cls(BLACK)
        if self.cleared:
            pyxel.text(132, 90, "STORM CLEARED!", LIME)
        else:
            pyxel.text(134, 90, "LEVEE BREACH!", RED)
        pyxel.text(130, 110, f"SCORE {self.score}", YELLOW)
        pyxel.text(130, 120, f"BEST  {self.best_score}", GRAY)
        pyxel.text(104, 150, "ENTER to retry", LIME)


if __name__ == "__main__":
    Game()
